services:
  web:
    build:
      context: .
      target: dev
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
